"""Generate deployment artifacts from one shared manifest. JSON is valid Compose YAML."""
import json
from pathlib import Path
from safe_paths import confined_path
root=Path(__file__).resolve().parent.parent
manifest=json.loads((root/'deploy/templates/stack.json').read_text())
env={
 'POSTGRES_HOST':'postgres:5432','POSTGRES_DB':'autodit','POSTGRES_USER':'autodit_app',
 'POSTGRES_PASSWORD_FILE':'/run/secrets/app_password',
 'AUTODIT_TENANT_ID':'${AUTODIT_TENANT_ID:-'+manifest['tenant_id']+'}',
 'AUTODIT_TENANT_NAME':'${AUTODIT_TENANT_NAME:-Audit workspace}',
 'AUTODIT_AUTH_MODE':'${AUTODIT_AUTH_MODE:-local}',
 'AUTODIT_PUBLIC_URL':'${AUTODIT_PUBLIC_URL:-http://localhost:8088}',
 'AUTODIT_ADMIN_PASSWORD_FILE':'/run/secrets/admin_password',
 'AUTODIT_DEMO_TOKEN_FILE':'/run/secrets/demo_token',
 'AUTODIT_OIDC_ISSUER':'${AUTODIT_OIDC_ISSUER:-}',
 'AUTODIT_OIDC_CLIENT_ID':'${AUTODIT_OIDC_CLIENT_ID:-}',
 'AUTODIT_OIDC_CLIENT_SECRET_FILE':'/run/secrets/oidc_secret',
}
base={'image':manifest['application_image'],'read_only':True,'cap_drop':['ALL'],'security_opt':['no-new-privileges:true'],
 'tmpfs':['/tmp:rw,noexec,nosuid,size=128m'],'environment':env,'secrets':['app_password','demo_token','oidc_secret','admin_password'],
 'networks':['audit'],'volumes':['snapshots:/data/snapshots'],'logging':{'driver':'k8s-file','options':{'max-size':'10m'}}}
api={**base,'command':['api'],'restart':'unless-stopped','healthcheck':{'test':['CMD','audit','healthcheck'],'interval':'10s','timeout':'4s','retries':12},'depends_on':{'postgres':{'condition':'service_healthy'}}}
worker={**base,'command':['worker'],'restart':'unless-stopped','stop_grace_period':'120s','environment':{**env,'AUTODIT_INBOX_DIR':'/data/inbox'},'volumes':['snapshots:/data/snapshots','../../inbox:/data/inbox:ro'],'depends_on':{'api':{'condition':'service_healthy'}}}
migrate={**base,'command':['migrate'],'profiles':['setup'],'environment':{**env,'POSTGRES_USER':'autodit_owner','POSTGRES_PASSWORD_FILE':'/run/secrets/db_password'},'secrets':['db_password','app_password','demo_token','oidc_secret','admin_password'],'depends_on':{'postgres':{'condition':'service_healthy'}}}
bootstrap={**base,'command':['bootstrap'],'profiles':['setup'],'depends_on':{'postgres':{'condition':'service_healthy'}}}
postgres={'image':manifest['postgres_image'],'restart':'unless-stopped','environment':{'POSTGRES_USER':'autodit_owner','POSTGRES_DB':'autodit','POSTGRES_PASSWORD_FILE':'/run/secrets/db_password','POSTGRES_INITDB_ARGS':'--auth-host=scram-sha-256'},'secrets':['db_password','app_password'],'volumes':['postgres_data:/var/lib/postgresql/data','../templates/postgres-init.sh:/docker-entrypoint-initdb.d/10-app.sh:ro'],'networks':['audit'],'healthcheck':{'test':['CMD-SHELL','pg_isready -U autodit_owner -d autodit'],'interval':'3s','timeout':'3s','retries':30},'logging':{'driver':'k8s-file','options':{'max-size':'10m'}}}
proxy={'image':manifest['proxy_image'],'restart':'unless-stopped','read_only':True,'cap_drop':['ALL'],'security_opt':['no-new-privileges:true'],'tmpfs':['/tmp:rw,noexec,nosuid,size=32m'],'ports':['${AUTODIT_BIND:-127.0.0.1}:${AUTODIT_PORT:-8088}:8080'],'networks':['audit'],'depends_on':{'api':{'condition':'service_healthy'}},'logging':{'driver':'k8s-file','options':{'max-size':'10m'}}}
compose={'name':'autodit','services':{'postgres':postgres,'migrate':migrate,'bootstrap':bootstrap,'api':api,'worker':worker,'proxy':proxy},'volumes':{'postgres_data':{},'snapshots':{}},'networks':{'audit':{'internal':True}},'secrets':{name:{'file':'../../secrets/'+name} for name in ['db_password','app_password','demo_token','oidc_secret','admin_password']}}
# Published ports need a return route on rootless Podman. Only the proxy joins
# this ingress bridge; financial data services remain on the internal network.
compose['networks']['ingress']={}
compose['services']['proxy']['networks']=['audit','ingress']
# Compose's file secrets become bind mounts and ignore mode/uid on several
# providers. Native Podman secrets remain readable by non-root service users
# without making the host's secret files world-readable.
compose['secrets']={'autodit_'+name:{'external':True} for name in ['db_password','app_password','demo_token','oidc_secret','admin_password']}
for service in compose['services'].values():
 if 'secrets' in service:
  service['secrets']=[{'source':'autodit_'+name,'target':name} for name in service['secrets']]
target=confined_path(root,'deploy/compose/compose.json')
target.parent.mkdir(parents=True,exist_ok=True)
with target.open('w',encoding='utf-8',newline='\n') as output:
 json.dump(compose,output,indent=2)
 output.write('\n')
# This unit deliberately invokes the same Compose artifact; it cannot drift
# into a different service or secret topology.
unit='''# Generated by scripts/deploy-gen.py
[Unit]
Description=Autodit continuous audit stack
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=%h/autodit
ExecStart=/usr/bin/podman compose --env-file .env -f deploy/compose/compose.json up -d postgres api worker proxy
ExecStop=/usr/bin/podman compose --env-file .env -f deploy/compose/compose.json stop -t 120
TimeoutStartSec=300
TimeoutStopSec=150

[Install]
WantedBy=default.target
'''
target=confined_path(root,'deploy/systemd/autodit.service')
target.parent.mkdir(parents=True,exist_ok=True)
with target.open('w',encoding='utf-8',newline='\n') as output:
 output.write(unit)
